export const NOTIFICATION_TYPE_RESOURCE_CREATED = 'ResourceCreated';

export const PRODUCT_PUBLISH_SUBSCRIPTION_MESSAGE_TYPE = 'ProductPublished';

export const PRODUCT_PUBLISH_SUBSCRIPTION_MESSAGE_TYPES = [
    PRODUCT_PUBLISH_SUBSCRIPTION_MESSAGE_TYPE,
];