export const NOTIFICATION_TYPE_RESOURCE_CREATED = 'ResourceCreated';

export const PRODUCT_PRICE_DISCOUNT_SET_SUBSCRIPTION_MESSAGE_TYPE = 'ProductPriceDiscountsSet';

export const PRODUCT_PRICE_DISCOUNT_SET_SUBSCRIPTION_MESSAGE_TYPES = [
    PRODUCT_PRICE_DISCOUNT_SET_SUBSCRIPTION_MESSAGE_TYPE,
];